version: "3"
services:
  astro:
    networks:
      - web
    container_name: astro
    build:
      dockerfile: ./deploy/astro/Dockerfile
    ports:
      - 9000
  proxy:
    networks:
      - web
    container_name: proxy 
    build:
      dockerfile: ./deploy/proxy/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:8080
      - 443:8081
networks:
  web:
