services:
  astro:
    env_file:
      - ./docker-compose.env
    networks:
      - web
    container_name: astro
    build:
      dockerfile: ./deploy/astro/Dockerfile
    volumes:
      - ./deploy/astro/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 9000
  proxy:
    env_file:
      - ./docker-compose.env
    networks:
      - web
    container_name: proxy
    image: nginx:alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt # Host-specific location of certificates
      - ./deploy/proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:8080
      - 443:8081
networks:
  web:
