services:
  astro:
    networks:
      - web
    container_name: astro
    build:
      dockerfile: ./deploy/astro/Dockerfile
    volumes:
      - ./deploy/astro/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - $ASTRO_DEFAULT_PORT
  proxy:
    networks:
      - web
    container_name: proxy
    image: nginx:alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt # Host-specific location of certificates
      - ./deploy/proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - 80:$PROXY_DEFAULT_PORT
      - 443:$PROXY_SECURED_PORT
networks:
  web:
