name: Continuous Delivery

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new version over SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_KEY }}
          script: |
            docker compose --env-file blog/docker-compose.env --project-directory blog down --remove-orphans --volumes --rmi all
            rm -rf blog
            git clone https://github.com/dubet/blog.git blog
            docker compose --env-file blog/docker-compose.env --project-directory blog up --build --detach --force-recreate --remove-orphans
