name: Deploy to Firebase Hosting

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Set up Yarn & Corepack
      run: |
        node --version
        corepack enable
        yarn set version stable
        yarn install
    - name: Build sources
      run: |
        yarn build
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DUBET_FR }}
        channelId: live
        projectId: dubet-fr
